const menu = [
  {
    id: 1,
    title: 'buttermilk pancakes',
    category: 'breakfast',
    price: 15.99,
    img: './images/item-1.jpeg',
    desc: `You think the recipe or book gives you all of the information you need to bake a successful cake.  `,
  },
  {
    id: 2,
    title: 'diner double',
    category: 'lunch',
    price: 13.99,
    img: './images/item-2.jpeg',
    desc: ` we give you foolproof step-by-step recipes, with color photos, with an understanding of WHY and HOW something works the way it does, so you can’t and won’t fail! `,
  },
  {
    id: 3,
    title: 'godzilla milkshake',
    category: 'shakes',
    price: 6.99,
    img: './images/item-3.jpeg',
    desc: ` we give you foolproof step-by-step recipes, with color photos, with an understanding of WHY and HOW something works the way it does, so you can’t and won’t fail!`,
  },
  {
    id: 4,
    title: 'country delight',
    category: 'breakfast',
    price: 20.99,
    img: './images/item-4.jpeg',
    desc: `Cakes have around since the time of the ancient Egyptians, and are believed to have been more like sweetened bread with the addition of honey, nuts and dried fruits than like the cake we know today. `,
  },
  {
    id: 5,
    title: 'egg attack',
    category: 'lunch',
    price: 22.99,
    img: './images/item-5.jpeg',
    desc: `Cakes lend themselves to limitless variations depending on the proportion of their ingredients, the way they are mixed, flavorings added to the basic ingredients, `,
  },
  {
    id: 6,
    title: 'oreo dream',
    category: 'shakes',
    price: 18.99,
    img: './images/item-6.jpeg',
    desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
  },
  {
    id: 7,
    title: 'bacon overflow',
    category: 'breakfast',
    price: 8.99,
    img: './images/item-7.jpeg',
    desc: `Cakes lend themselves to limitless variations depending on the proportion of their ingredients, the way they are mixed, flavorings added to the basic ingredients,`,
  },
  {
    id: 8,
    title: 'american classic',
    category: 'lunch',
    price: 12.99,
    img: './images/item-8.jpeg',
    desc: `Cakes have around since the time of the ancient Egyptians, and are believed to have been more like sweetened bread with the addition of honey, nuts and dried fruits than like the cake we know today.  `,
  },
  {
    id: 9,
    title: 'quarantine buddy',
    category: 'shakes',
    price: 16.99,
    img: './images/item-9.jpeg',
    desc: ` (It may also may refer to any round, flat disk of food, such as a pancake or even a yeasted sweet (coffee) cake, discussed in other sections.)`,
  },
];
export default menu;
